kimdanbin/travel-shooting

src/main/java/com/example/travelshooting/common/BaseDtoDataType.java, src/main/java/com/example/travelshooting/common/CommonListResDto.java, src/main/java/com/example/travelshooting/common/CommonResDto.java, src/main/java/com/example/travelshooting/common/Const.java
CommonResDto를 상속 받는 게 아니라 BaseDtoDataType을 상속 받도록 수정
=> fix: CommonResDto

src/main/java/com/example/travelshooting/common/BaseDtoDataType.java, src/main/java/com/example/travelshooting/local/LocalController.java, src/main/java/com/example/travelshooting/local/LocalResDto.java, src/main/java/com/example/travelshooting/local/LocalService.java
- 장소 검색 기능 구현
- BaseDtoDataType 타입을 클래스에서 인터페이스로 수정
=> feat: 장소 검색

src/main/java/com/example/travelshooting/local/LocalController.java, src/main/java/com/example/travelshooting/local/LocalResDto.java
=> fix: 파라미터 필수

src/main/java/com/example/travelshooting/comment/Comment.java, src/main/java/com/example/travelshooting/company/controller/CompanyController.java, src/main/java/com/example/travelshooting/company/repository/CompanyRepository.java, src/main/java/com/example/travelshooting/company/service/CompanyService.java, src/main/java/com/example/travelshooting/poster/Poster.java, src/main/java/com/example/travelshooting/user/User.java
- 레저/티켓 업체 전체 조회 기능 구현
- 레저/티켓 업체 단건 조회 기능 구현
=> feat: 레저/티켓 업체 조회

src/main/java/com/example/travelshooting/restaurant/controller/RestaurantController.java
=> fix: url 변경

src/main/java/com/example/travelshooting/company/Company.java, src/main/java/com/example/travelshooting/company/controller/CompanyController.java, src/main/java/com/example/travelshooting/company/dto/UpdateCompanyReqDto.java, src/main/java/com/example/travelshooting/company/service/CompanyService.java
=> feat: 레저/티켓 업체 수정

src/main/java/com/example/travelshooting/company/controller/CompanyController.java, src/main/java/com/example/travelshooting/company/service/CompanyService.java
=> feat: 레저/티켓 업체 삭제

src/main/java/com/example/travelshooting/company/service/CompanyService.java, src/main/java/com/example/travelshooting/product/Product.java, src/main/java/com/example/travelshooting/product/controller/ProductController.java, src/main/java/com/example/travelshooting/product/dto/CreateProductReqDto.java, src/main/java/com/example/travelshooting/product/dto/CreateProductResDto.java, src/main/java/com/example/travelshooting/product/repository/ProductRepository.java, src/main/java/com/example/travelshooting/product/service/ProductService.java
- 레저/티켓 상품 등록 기능 구현
- quantity 필드 추가
=> feat: 레저/티켓 상품 등록

src/main/java/com/example/travelshooting/product/Product.java, src/main/java/com/example/travelshooting/product/controller/ProductController.java, src/main/java/com/example/travelshooting/product/dto/UpdateProductReqDto.java, src/main/java/com/example/travelshooting/product/dto/UpdateProductResDto.java, src/main/java/com/example/travelshooting/product/repository/ProductRepository.java, src/main/java/com/example/travelshooting/product/service/ProductService.java
=> feat: 레저/티켓 상품 수정

src/main/java/com/example/travelshooting/product/controller/ProductController.java, src/main/java/com/example/travelshooting/product/service/ProductService.java
=> feat: 레저/티켓 상품 삭제

src/main/java/com/example/travelshooting/part/repository/PartRepository.java, src/main/java/com/example/travelshooting/part/service/PartService.java, src/main/java/com/example/travelshooting/reservation/controller/ReservationController.java, src/main/java/com/example/travelshooting/reservation/dto/ReservationReqDto.java, src/main/java/com/example/travelshooting/reservation/dto/ReservationResDto.java, src/main/java/com/example/travelshooting/reservation/repository/ReservationRepository.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java
- 예약 취소
- 예약 전체 조회
- 예약 단 건 조회
=> feat: 사용자 기준 레저/티켓 예약 추가 기능 구현

src/main/java/com/example/travelshooting/part/dto/PartResDto.java, src/main/java/com/example/travelshooting/part/repository/PartRepository.java, src/main/java/com/example/travelshooting/part/service/PartService.java, src/main/java/com/example/travelshooting/product/controller/ProductController.java, src/main/java/com/example/travelshooting/product/dto/ProductDetailResDto.java, src/main/java/com/example/travelshooting/product/dto/ProductResDto.java, src/main/java/com/example/travelshooting/product/repository/ProductRepository.java, src/main/java/com/example/travelshooting/product/service/ProductService.java
- 레저/티켓 상품 전체 조회 기능 구현
- 레저/티켓 상품 단 건 조회 기능 구현
=> feat: 레저/티켓 상품 조회

src/main/java/com/example/travelshooting/part/Part.java, src/main/java/com/example/travelshooting/part/controller/PartController.java, src/main/java/com/example/travelshooting/part/dto/CreatePartReqDto.java, src/main/java/com/example/travelshooting/part/dto/PartResDto.java, src/main/java/com/example/travelshooting/part/service/PartService.java, src/main/java/com/example/travelshooting/product/dto/ProductDetailResDto.java, src/main/java/com/example/travelshooting/product/service/ProductService.java
- 레저/티켓 상품 일정 생성 기능 구현
- 서비스 간 의존성 개선
=> feat: 레저/티켓 일정 생성

src/main/java/com/example/travelshooting/common/Const.java, src/main/java/com/example/travelshooting/config/SecurityConfig.java, src/main/java/com/example/travelshooting/poster/service/PosterService.java, src/main/java/com/example/travelshooting/restaurant/Restaurant.java, src/main/java/com/example/travelshooting/restaurant/controller/RestaurantController.java, src/main/java/com/example/travelshooting/restaurant/dto/GgRestaurantApiDto.java, src/main/java/com/example/travelshooting/restaurant/dto/GgRestaurantResDto.java, src/main/java/com/example/travelshooting/restaurant/service/GgRestaurantService.java, src/main/resources/application.properties
- RestaurantService 클래스명을 GgRestaurantService 명으로 변경
- 도, 시 컬럼 추가
=> fix: 클래스명 수정 및 api url 환경변수 설정

src/main/java/com/example/travelshooting/restaurant/service/GgRestaurantService.java
경기도 음식점 정보 저장 서비스에 타임아웃 예외처리 추가
=> fix: 타임아웃 예외처리

src/main/java/com/example/travelshooting/reservation/repository/ReservationRepository.java, src/main/java/com/example/travelshooting/reservation/service/ReservationPartnerService.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java, src/main/java/com/example/travelshooting/user/service/UserService.java
- 정해진 인원 수를 넘길 경우, 예약 신청 못하도록 수정
- findUserByEmail() 메서드를 getAuthenticatedUser() 메서드로 수정
=> fix: 레저/티켓 예약 및 취소

src/main/java/com/example/travelshooting/enums/ReportType.java, src/main/java/com/example/travelshooting/report/Report.java, src/main/java/com/example/travelshooting/report/controller/ReportController.java, src/main/java/com/example/travelshooting/report/dto/ReportReqDto.java, src/main/java/com/example/travelshooting/report/dto/ReportResDto.java, src/main/java/com/example/travelshooting/report/repository/ReportRepository.java, src/main/java/com/example/travelshooting/report/service/ReportService.java
- 신고 기능 관련 구성 요소 추가
- 포스터 신고 기능 구현
- 댓글 신고 기능 구현
- 임시 유저 수정
=> feat: 신고 기능

src/main/java/com/example/travelshooting/reservation/repository/ReservationRepository.java
=> fix: findTotalNumberByPartId() 쿼리 수정

src/main/java/com/example/travelshooting/report/controller/ReportController.java, src/main/java/com/example/travelshooting/report/repository/ReportRepository.java, src/main/java/com/example/travelshooting/report/service/ReportService.java
- 신고 내역 전체 조회 기능 구현
- 신고 내역 단 건 조회 기능 구현
=> feat: 신고 내역 조회

src/main/java/com/example/travelshooting/company/repository/CompanyRepository.java, src/main/java/com/example/travelshooting/company/service/CompanyService.java, src/main/java/com/example/travelshooting/part/repository/PartRepository.java, src/main/java/com/example/travelshooting/part/service/PartService.java, src/main/java/com/example/travelshooting/product/repository/ProductRepository.java, src/main/java/com/example/travelshooting/report/repository/ReportRepository.java
- IllegalArgumentException을 ResponseStatusException으로 변경
=> refactor: 예외 처리 수정

src/main/java/com/example/travelshooting/poster/service/PosterService.java, src/main/java/com/example/travelshooting/restaurant/controller/RestaurantController.java, src/main/java/com/example/travelshooting/restaurant/controller/RestaurantSearchController.java, src/main/java/com/example/travelshooting/restaurant/repository/RestaurantRepository.java, src/main/java/com/example/travelshooting/restaurant/service/GgRestaurantService.java, src/main/java/com/example/travelshooting/restaurant/service/RestaurantService.java
- 음식점 정보 저장 로직 리팩토링
- 음식점 아이디로 음식점 찾는 findById를 디폴트 메서드로 변경
- RestaurantService 클래스에 findRestaurantById 메서드 구현
- PosterService 클래스에서 사용하는 맛집 정보 찾기 메서드를 "restaurantService.findRestaurantById" 로 변경
=> fix: get -> find로 메서드 수정

src/main/java/com/example/travelshooting/common/Const.java, src/main/java/com/example/travelshooting/config/SecurityConfig.java
=> fix: 상수로 관리

src/main/java/com/example/travelshooting/company/controller/CompanyController.java, src/main/java/com/example/travelshooting/company/dto/CompanyReqDto.java, src/main/java/com/example/travelshooting/company/service/CompanyService.java, src/main/java/com/example/travelshooting/part/controller/PartController.java, src/main/java/com/example/travelshooting/part/dto/CreatePartReqDto.java, src/main/java/com/example/travelshooting/part/service/PartService.java, src/main/java/com/example/travelshooting/product/controller/ProductController.java, src/main/java/com/example/travelshooting/product/dto/CreateProductReqDto.java, src/main/java/com/example/travelshooting/product/service/ProductService.java, src/main/java/com/example/travelshooting/report/controller/ReportController.java, src/main/java/com/example/travelshooting/report/service/ReportService.java
- DTO 값 추출 방식 변경
- get -> find 메서드명 수정
=> fix: RequestDto를 컨트롤러 계층에서만 사용하도록 수정

src/main/java/com/example/travelshooting/local/controller/LocalController.java, src/main/java/com/example/travelshooting/local/dto/LocalResDto.java, src/main/java/com/example/travelshooting/local/service/LocalService.java
- 장소 검색 시, "장소 검색 완료" 메시지도 포함 시킴
=> refactor: 장소 검색 리팩토링

src/main/java/com/example/travelshooting/restaurant/dto/GgRestaurantResDto.java, src/main/java/com/example/travelshooting/restaurant/dto/RestaurantResDto.java
=> refactor: responseDto 수정

build.gradle, src/main/java/com/example/travelshooting/config/QueryDslConfig.java
- querydsl 의존성 추가
- QueryDslConfig 생성
=> feat: QueryDslConfig 생성

src/main/java/com/example/travelshooting/poster/test/TestSearchController.java, src/main/java/com/example/travelshooting/poster/test/TestSearchResDto.java, src/main/java/com/example/travelshooting/poster/test/TestSearchService.java
- 임시 테스트 파일
- querydsl 적용해 검색 테스트
=> feat: 좋아요순 포스트 검색 기능

src/main/java/com/example/travelshooting/poster/test/TestSearchController.java, src/main/java/com/example/travelshooting/poster/test/TestSearchResDto.java, src/main/java/com/example/travelshooting/poster/test/TestSearchService.java
=> fix: 경비 검색 조건 추가

src/main/java/com/example/travelshooting/reservation/entity/Reservation.java, src/main/java/com/example/travelshooting/reservation/repository/ReservationRepository.java, src/main/java/com/example/travelshooting/restaurant/dto/RestaurantResDto.java, src/main/java/com/example/travelshooting/restaurant/repository/RestaurantRepository.java, src/main/java/com/example/travelshooting/restaurant/service/RestaurantService.java
=> refactor: 맛집 검색 리팩토링

src/main/java/com/example/travelshooting/payment/service/PaymentService.java, src/main/java/com/example/travelshooting/reservation/controller/ReservationController.java, src/main/java/com/example/travelshooting/reservation/controller/ReservationPartnerController.java, src/main/java/com/example/travelshooting/reservation/dto/ReservationReqDto.java, src/main/java/com/example/travelshooting/reservation/dto/ReservationResDto.java, src/main/java/com/example/travelshooting/reservation/entity/Reservation.java, src/main/java/com/example/travelshooting/reservation/repository/ReservationRepository.java, src/main/java/com/example/travelshooting/reservation/service/ReservationPartnerService.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java
- 메서드명 수정
- 기본 타입에서 참조형 타입으로 변경
- resDto 필드 final 선언
=> refactor: 예약 메서드명 및 responseDto

src/main/java/com/example/travelshooting/payment/entity/Payment.java, src/main/java/com/example/travelshooting/payment/service/PaymentService.java, src/main/resources/application.properties
- 환경변수 추가
- payment 테이블에 결제수단 정보 저장되도록 추가
- 결제수단 : card or money
=> refactor: 환경변수 및 결제수단 추가

src/main/java/com/example/travelshooting/restaurant/controller/RestaurantController.java, src/main/java/com/example/travelshooting/restaurant/dto/RestaurantSearchResDto.java, src/main/java/com/example/travelshooting/restaurant/service/RestaurantService.java
여러 포스터가 동일한 맛집을 추천할 수 있기 때문에 group by 추가 및 count 필드 추가
=> fix: 맛집 검색

src/main/java/com/example/travelshooting/common/Const.java, src/main/java/com/example/travelshooting/local/controller/LocalController.java, src/main/java/com/example/travelshooting/local/service/LocalService.java, src/main/java/com/example/travelshooting/report/service/ReportService.java
- 신고 누적 횟수 상수 관리
- 장소 검색 page 디폴트 값 상수 관리
- pageable 안 쓰고 페이징 처리
=> refactor: 상수 관리 및 장소 검색 페이징

src/main/java/com/example/travelshooting/company/repository/CompanyRepository.java, src/main/java/com/example/travelshooting/company/service/CompanyService.java, src/main/java/com/example/travelshooting/product/repository/ProductRepository.java, src/main/java/com/example/travelshooting/product/service/ProductService.java
- 디폴트 메서드 적용
- getNumber() -> getHeadCount()
=> refactor: 디폴트 메서드 적용

src/main/java/com/example/travelshooting/payment/service/PaymentService.java
삭제 처리된 예약 또는 없는 예약을 결제 시도할 때, 404 예외 처리 되도록 수정
=> fix: 예외 처리

src/main/java/com/example/travelshooting/part/entity/Part.java
=> fix: part entity

build.gradle, src/main/java/com/example/travelshooting/config/SchedulerConfig.java, src/main/java/com/example/travelshooting/enums/ReservationStatus.java, src/main/java/com/example/travelshooting/reservation/entity/Reservation.java, src/main/java/com/example/travelshooting/reservation/repository/ReservationRepository.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java
- 예약 승인일로부터 다음 날 오후 6시까지 결제를 안 한 경우, 예약 만료 처리 함
- 매일 오후 6시에 스케쥴러 실행
- EXPIRED 상태 값 부여
- is_deleted = true로 변경
=> feat: 예약 스케쥴러 구현

src/main/java/com/example/travelshooting/part/controller/PartController.java, src/main/java/com/example/travelshooting/part/dto/CreatePartReqDto.java, src/main/java/com/example/travelshooting/part/dto/PartResDto.java, src/main/java/com/example/travelshooting/part/dto/UpdatePartReqDto.java, src/main/java/com/example/travelshooting/part/entity/Part.java, src/main/java/com/example/travelshooting/part/repository/PartRepository.java, src/main/java/com/example/travelshooting/part/service/PartService.java, src/main/java/com/example/travelshooting/product/controller/ProductController.java, src/main/java/com/example/travelshooting/product/dto/CreateProductReqDto.java, src/main/java/com/example/travelshooting/product/dto/CreateProductResDto.java, src/main/java/com/example/travelshooting/product/dto/ProductDetailResDto.java, src/main/java/com/example/travelshooting/product/dto/ProductResDto.java, src/main/java/com/example/travelshooting/product/dto/UpdateProductReqDto.java, src/main/java/com/example/travelshooting/product/dto/UpdateProductResDto.java, src/main/java/com/example/travelshooting/product/entity/Product.java, src/main/java/com/example/travelshooting/product/service/ProductService.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java
- 상품 quantity 제거
- 상품 saleStartAt, saleEndAt 추가
- 일정 headCount -> maxQuantity
=> fix: 컬럼 수정

src/main/java/com/example/travelshooting/enums/PaymentStatus.java, src/main/java/com/example/travelshooting/enums/RefundType.java, src/main/java/com/example/travelshooting/payment/entity/Payment.java, src/main/java/com/example/travelshooting/payment/service/PaymentService.java
=> fix: 결제 테이블 수정

src/main/java/com/example/travelshooting/config/WebConfig.java, src/main/java/com/example/travelshooting/payment/controller/PaymentController.java, src/main/java/com/example/travelshooting/payment/dto/PaymentCompletedResDto.java, src/main/java/com/example/travelshooting/payment/entity/Payment.java, src/main/java/com/example/travelshooting/payment/service/PaymentService.java
- 결제 취소 url에서 paymentId를 가져오기 때문에 처음에는 tid 없이 저장하고 이후 tid update
- cancelPrice 기본값 0 지정
- 결제 실패 시, OK가 아니라 Bad Request 상태 코드가 나오도록 수정
=> fix: 결제 로직 수정

src/main/java/com/example/travelshooting/reservation/repository/ReservationRepository.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java
- 예약 날짜는 판매 기간 중에서만 선택할 수 있음
- 해당 날짜에 예약한 내역이 있으면 예외처리
- ex) 일정1의 quantity가 10일 경우, 날짜별로 10명까지 예약 가능
=> fix: 예약 신청 예외 처리 수정

src/main/java/com/example/travelshooting/common/Const.java, src/main/java/com/example/travelshooting/enums/RefundPolicy.java, src/main/java/com/example/travelshooting/payment/controller/PaymentController.java, src/main/java/com/example/travelshooting/payment/dto/PaymentCancelResDto.java, src/main/java/com/example/travelshooting/payment/entity/Payment.java, src/main/java/com/example/travelshooting/payment/repository/PaymentRepository.java, src/main/java/com/example/travelshooting/payment/service/PaymentService.java, src/main/java/com/example/travelshooting/reservation/repository/ReservationRepository.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java, src/main/resources/application.properties
- 환불 정책은 enum 으로 관리
- 전 날 결제 취소는 30% 환불
- 전 날 취소가 아니면 전액 환불
- 당일 결제 취소 불가
=> feat: 결제 취소 기능 구현

src/main/java/com/example/travelshooting/common/Const.java, src/main/java/com/example/travelshooting/config/WebConfig.java, src/main/java/com/example/travelshooting/enums/ReservationStatus.java, src/main/java/com/example/travelshooting/reservation/entity/Reservation.java, src/main/java/com/example/travelshooting/reservation/repository/ReservationRepository.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java
- 메서드 재사용 하기 위해 로직 수정
- 사용자가 예약 취소할 경우, is_deleted = true 및 status = CANCELED
- boolean 타입으로 하면 메서드 재사용을 하기에는 한정적이기 때문에 Optional 타입으로 변경
=> fix: 예약 메서드 재사용

src/main/java/com/example/travelshooting/common/Const.java, src/main/java/com/example/travelshooting/config/MailConfig.java, src/main/java/com/example/travelshooting/config/WebConfig.java, src/main/java/com/example/travelshooting/notification/service/MailService.java, src/main/java/com/example/travelshooting/reservation/service/ReservationMailService.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java, src/main/resources/application.properties, src/main/resources/templates/mail/reservation.html
- 타임리프 사용해 메일 양식 적용
- 권한과 예약 상태에 따라 전송되는 메일이 다름
- 일단 사용자가 예약 신청을 할 때 신청 완료 메일을 받을 수 있도록 구현
=> feat: 메일 알림 기능 구현

src/main/java/com/example/travelshooting/part/dto/CreatePartReqDto.java, src/main/java/com/example/travelshooting/part/dto/UpdatePartReqDto.java
=> fix: 최대값 지정 애노테이션 변경

src/main/java/com/example/travelshooting/common/Const.java, src/main/java/com/example/travelshooting/enums/NotificationStatus.java, src/main/java/com/example/travelshooting/enums/NotificationType.java, src/main/java/com/example/travelshooting/notification/dto/NotificationDetails.java, src/main/java/com/example/travelshooting/notification/entity/Notification.java, src/main/java/com/example/travelshooting/notification/repository/NotificationRepository.java, src/main/java/com/example/travelshooting/notification/service/NotificationService.java, src/main/java/com/example/travelshooting/reservation/entity/Reservation.java, src/main/java/com/example/travelshooting/reservation/service/ReservationMailService.java, src/main/java/com/example/travelshooting/reservation/service/ReservationPartnerService.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java, src/main/resources/templates/mail/reservation.html
- 일단 예약 알림만 저장할 수 있도록 설계하였기 때문에 예약 기본키를 외래키로 받아서 사용
- 알림 상태 및 타입을 enum으로 관리
- 업체가 예약 승인 또는 거절을 하면 사용자만 메일을 받을 수 있도록 수정
=> feat: 알림 테이블 생성

src/main/java/com/example/travelshooting/common/Const.java, src/main/java/com/example/travelshooting/config/SchedulerConfig.java, src/main/java/com/example/travelshooting/notification/entity/Notification.java, src/main/java/com/example/travelshooting/notification/service/NotificationService.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java
알림이 쌓이면 조회할 알림 내역이 많아지기 때문에 알림을 30일만 보관하고, 이후에는 삭제 처리하도록 스케줄러 추가
=> feat: 30일 지난 알림 자동 삭제

src/main/java/com/example/travelshooting/payment/controller/PaymentController.java, src/main/java/com/example/travelshooting/payment/dto/PaymentResDto.java, src/main/java/com/example/travelshooting/payment/entity/Payment.java, src/main/java/com/example/travelshooting/payment/service/PaymentService.java
=> feat: 사용자 결제 내역 조회 기능 구현

src/main/java/com/example/travelshooting/config/SchedulerConfig.java
스케줄러를 사용해 서버가 실행되면 자동으로 음식점 정보를 테이블에 저장할 수 있도록 함
=> feat: 음식점 정보 자동 저장

src/main/java/com/example/travelshooting/comment/repository/CommentRepository.java, src/main/java/com/example/travelshooting/comment/service/CommentService.java, src/main/java/com/example/travelshooting/poster/service/PosterService.java, src/main/java/com/example/travelshooting/report/service/ReportService.java
=> fix: 신고 누적 시 삭제 처리 로직 수정

src/main/java/com/example/travelshooting/reservation/controller/ReservationController.java, src/main/java/com/example/travelshooting/reservation/controller/ReservationPartnerController.java, src/main/java/com/example/travelshooting/reservation/dto/ReservationResDto.java, src/main/java/com/example/travelshooting/reservation/repository/ReservationRepository.java, src/main/java/com/example/travelshooting/reservation/service/ReservationPartnerService.java, src/main/java/com/example/travelshooting/reservation/service/ReservationService.java
- 동시성 제어 하기 전, 임시 리팩토링
- 동시성 제어 로직 추가 후, 리팩토링 추가로 할 예정
=> refactor: 예약 리팩토링

src/main/java/com/example/travelshooting/restaurant/controller/RestaurantController.java
=> fix: pageable 수정

src/main/java/com/example/travelshooting/company/repository/CompanyRepository.java, src/main/java/com/example/travelshooting/company/service/CompanyService.java
- 관리자는 본인 업체 등록할 수 없음
- 삭제된 업체명으로 등록할 수 없음
=> fix: 업체 생성 예외처리 추가

src/main/java/com/example/travelshooting/common/Const.java, src/main/java/com/example/travelshooting/company/service/CompanyService.java, src/main/java/com/example/travelshooting/reservation/service/ReservationPartnerService.java
- 캐싱 적용 시 페이지 사이즈 고정을 위해 상수로 관리
=> fix: 페이지 사이즈 상수 관리

src/main/java/com/example/travelshooting/product/controller/ProductController.java, src/main/java/com/example/travelshooting/product/dto/ProductResDto.java, src/main/java/com/example/travelshooting/product/repository/ProductCustomRepository.java, src/main/java/com/example/travelshooting/product/repository/ProductCustomRepositoryImpl.java, src/main/java/com/example/travelshooting/product/repository/ProductRepository.java, src/main/java/com/example/travelshooting/product/service/ProductService.java
=> fix: 상품 조회 동적 쿼리 적용
